### PR TITLE
Refactoring PlottableData management

### PR DESCRIPTION
**Pull request by grussorusso**
This PR aims at integrating `DataSelection` entities into `Plot`. At the moment, we have:
- added optional `shift` and `scale` fields for each axis, so that you can shift and scale input data
- deprecated the old `dataSelectionString`
- replacing `dataSelectionString` with `DataSelection` instances

There is still work to do:
- adjusting the GUI to support new data selection features

### CODE REVIEW

**Review by LucaF89 — COMMENTED** [review]
I have just seen...good improvement

**Review by LucaF89 — APPROVED** [review]

**Comment by LucaF89** [comment]
I approved your pull request. If you agree, do the merge and open a new PR for integration and GUI refactoring. 
Bye Luca

**Comment by grussorusso** [comment]
Thanks! I think it is better to continue working on this feature here, and
wait for completion before merging it... the improvement at the moment is
really small!

Il 03/mag/2017 00:41, "Luca" <notifications@github.com> ha scritto:

**Comment by grussorusso** [comment]
I integrated `PlottableDataController` into `AddDialog` for adding new data. At the moment, some features are broken:
- table which used to display datasets
- dataset editing

**Comment by LucaF89** [comment]
We have to create new methods in the controller to get current project PlottableItem...

**Review by fededido — COMMENTED** [review]
Good job :)

**Pull request merged**
