### PR TITLE
New layout for main window

### PR DESCRIPTION
**Pull request by grussorusso**
This PR aims at improving the layout of the main window, as described in the attached image:
gui-snapshot

### CODE REVIEW

**Comment by grussorusso** [comment]
In the firts commits, I added a `JSplitPane` in the main window, dividing it in two horizontally split panels. `PreviewPanel` at the moment is empty. I also created `panel` package in `gui` and removed some unused classes by the way.

**Comment by LucaF89** [comment]
@childerico if you agree with me, I'm going to create the `BottomPanel` and the `OverviewPanel`?

**Comment by grussorusso** [comment]
@LucaF89 ok!

**Comment by LucaF89** [comment]
Next step for the previewer is to scale the image with the panel space. What do you think about it?

**Comment by LucaF89** [comment]
We need also to update the preview on plot changes. Can you create some task to split the work?

**Comment by grussorusso** [comment]
As regards the image scaling, I think we could also leave it as an issue and resolve it immediately after merging this PR.

Before merging, we should 1) ensure the plot is updated at every change, and 2) integrate the BottomPanel with `PlotController` since at the moment whatever you set there is not applied in the preview. If we have enough time, we could also fix the image scaling issue. I will create a few tasks.

**Comment by LucaF89** [comment]
If you want I can update the Plot using the PlotController and you can use the observer to get the preview updated.

**Comment by grussorusso** [comment]
Ok!

Il 13/giu/2017 14:15, "Luca" <notifications@github.com> ha scritto:

If you want I can update the Plot using the PlotController and you can use
the observer to get the preview updated.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hopandfork/jgnuplot/pull/38#issuecomment-308096926>,
or mute
the thread

**Review by LucaF89 — APPROVED** [review]
Ok it's enough for this PR!

**Pull request merged**
