### PR TITLE
Adds an 'Add function' button

### PR DESCRIPTION
**Pull request by grussorusso**
Adds a button in the bottom toolbar to easily add a new function.

### CODE REVIEW

**Review by LucaF89 — COMMENTED** [review]
@childerico maybe you have to use an intuitive name for the variable bAdd bAdd1 bAdd2...what do you think???

**Comment by grussorusso** [comment]
@LucaF89 You are right, but until we have a single 'Add' button managing datafiles, labels, and variables, it is difficult to find a meaningful name.

We should probably refactor the whole panel containing buttons in the main window, creating different buttons for managing different entities.

**Comment by LucaF89** [comment]
I can approve your PR but in the future we have to integrate the buttons directly in the tabs. We have to move code out of the entry point and create views capable of completely taking care of a particular feature.

**Review by LucaF89 — APPROVED** [review]

**Comment by grussorusso** [comment]
Probably we'd better refactor the whole panel in the main window...and reject this little change

**Comment by LucaF89** [comment]
@childerico I agree with your last consideration...close the PR

**Pull request closed without merging**
