### PR TITLE
Updates views' control introducing presenters

### PR DESCRIPTION
**Pull request by LucaF89**
- Creates a new package named presenter to develop the views' control
indipendently from the gui.
- Creates BottomPresenter to manage a BottomInterface object.

Signed-off-by: LucaF89 <luca.fulgieri@gmail.com>

### CODE REVIEW

**Comment by LucaF89** [comment]
`PreviewPanel` needs a `PreviewPresenter` and a `PreviewInterface`. Also the entry point `JGP` needs to be redesigned in the same way.

Before closing this PR I'm thinking of the possibility to move the `Observer` on the `Presenter` from the view. @childerico give me a feedback please...

**Comment by grussorusso** [comment]
@LucaF89 it is OK for me

**Review by grussorusso — APPROVED** [review]
Everything is OK up to this point. If you want, we can continue working on this before merging.

You should fetch the changes from `master` before closing the PR anyway, because there are some conflicts.

**Comment by LucaF89** [comment]
@childerico I merged the PR with the master but if you add a Constants in the FunctionDialog you get the following error:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.text.DecimalFormat.format(DecimalFormat.java:507)
	at java.text.Format.format(Format.java:157)
	at org.pushingpixels.substance.api.renderers.SubstanceDefaultTableCellRenderer$DoubleRenderer.setValue(SubstanceDefaultTableCellRenderer.java:235)
	at org.pushingpixels.substance.api.renderers.SubstanceDefaultTableCellRenderer.getTableCellRendererComponent(SubstanceDefaultTableCellRenderer.java:393)
	at javax.swing.JTable.prepareRenderer(JTable.java:5723)
	[...]
```

**Comment by grussorusso** [comment]
I verified that the bug you reported exists on `master` too. I think we should create an issue for that, and ignoring it in this PR.

**Comment by LucaF89** [comment]
@childerico I have just pushed the MainPanel moving code away from the entry point. I think we have to create the `PreviewInterface` and `PreviewInterface` to close this PR. Are you agree?

**Comment by grussorusso** [comment]
I've just added `PreviewPresenter` and `PreviewInterface`. Review the changes before merging.

**Comment by LucaF89** [comment]
@childerico We did so much and we can improve it. I'd like your code and what you think we have to do now???Can I merge the PR???May be also the Table have to be managed with the presenters' approach...

**Comment by grussorusso** [comment]
I think we could improve the code in two directions:
1) making the Interfaces less coupled with the Swing based implementation of the Panels (we have already talked about this point);
2) extending the MVP approach to other components, as you suggest.

However, we have been working on this PR for a long time so far! I'd suggest that we merge this PR now. We could create new (and smaller) PRs later for extending this one.

**Pull request merged**
