### PR TITLE
Updates the project's structure

### PR DESCRIPTION
**Pull request by LucaF89**
- Updates the project's structure to use the MVC pattern.
- Removes the empty class gui.DatasetTableRow.
- Creates AddDialogController and two new abstractions Project and Settings.

### CODE REVIEW

**Review by grussorusso — COMMENTED** [review]
I agree with most of the proposed changes. But, I don't like having a `dialog` subpackage inside `control`. Dialog is something related to the View imho. For example, the `AddDialogController` that is introduced by this PR is not a controller in my opinion. I would expect something like "AddPlottableItemsController", which communicates with a View (maybe a dialog).

**Comment by LucaF89** [comment]
Ok @childerico I rename the class. You are right it is a better abstraction but I prefer a controller that manages the CRUD. What do you think about "PlottableItemsController"?

**Comment by LucaF89** [comment]
@childerico I have done the changes

**Review by grussorusso — APPROVED** [review]
Ok!

**Pull request merged**
